### ISSUE TITLE
Windows - NPM Install - Fibers C++ runtime library error 

### ISSUE THREAD

**Issue by matt4446** [Icenium/icenium-cli#1371]
Win 10 npm install 

Same problem I had with the nativescript CLI... 
https://github.com/NativeScript/nativescript-cli/issues/1348

![snip_20160315223745](https://cloud.githubusercontent.com/assets/1550939/13796434/a120f838-eafe-11e5-845e-d0bd23a9db86.png)

The related issue was updated here: 
https://github.com/laverdet/node-fibers/issues/262#issuecomment-163483884

Let me know if you need any more information (I'll be in Ireland Thursday - Monday if I'm acting silent) .

Thanks, 
Matt

**Comment by rosen-vladimirov** [comment]
Hey @matt4446 ,

We've updated our fibers dependency and the fix will be included in our next official release. You'll have to use Node.js 6.x.x in order to get the new binary, where this fix is included.

**Comment by matt4446** [comment]
Thanks @rosen-vladimirov. Less recompiling for me. I think I've already jumped up to 6.x...I'll check that it works on one of the evenings soon. V2.1 of NatieScript still required me (as of last week) to throw in the custom fibers binaries in. Is it updated there as well? If so it could be that I'm still on 5.x and just requires an upgrade.
