### ISSUE TITLE
Could not start App in Simulator with CLI

### ISSUE THREAD

**Issue by viktorstaikov** [Icenium/icenium-cli#1431]
Hi guys,

My project was developed in VS2013 with the extension.
After I have installed the CLI and Sublime package and tried to run the app in Simulator, it failed with error FUTURE_PROJECT_VER. I saw in your release notes for 2.8.2 that this was fixed.
Inside *.abproject* my *projectVersion* is *1.3*.

> $ appbuilder --version
> 3.2.4-662

**Comment by rosen-vladimirov** [comment]
Hi @viktorstaikov ,

The `projectVersion` property of `.abproject` is used for internal purposes and it's value must be 1.
In order to manage your package's version, you should use `BundleVersion` property in .abproject

Hope this helps :)
