### ISSUE TITLE
Change the info message of $ appbuilder doctor

### ISSUE THREAD

**Issue by ikoevska** [Icenium/icenium-cli#1477]
Currently, at the end of the doctor command output, we print:

> These warnings are just used to help the AppBuilder maintainers with debugging if you file an issue.
Please ignore them if everything you use AppBuilder for is working fine.

Can we change this to:

> When you file an issue, these warnings will help the AppBuilder team to investigate, identify, and resolve the report. Please, ignore them if you are not experiencing any issues with AppBuilder.

**Comment by nirinchev** [comment]
Closed by #1489
