### ISSUE TITLE
graceful-fs v3.0.0 and before will fail on node releases >= v7.0.

### ISSUE THREAD

**Issue by stephenfeather** [Icenium/icenium-cli#1498]
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible.

├─┬ appbuilder@3.3.2
│ ├─┬ gaze@0.5.1
│ │ └─┬ globule@0.1.0
│ │   └─┬ glob@3.1.21
│ │     └── graceful-fs@1.2.3

This stems from using an older and outdated version of gaze (v 1.1.0 as of today). There is also a minimatch flaw that should be resolved when gaze is updated as well.

**Comment by rosen-vladimirov** [comment]
Hi @stephenfeather ,
We've updated the gaze dependency in our latest release, so you should not see the warning anymore :)
