### ISSUE TITLE
Haven't you guys had enough problems with TypeScript node-fibers?

### ISSUE THREAD

**Issue by tailsu** [Icenium/icenium-cli#1572]
How 'bout phasing out TypeScript in favor of ES7 via Babel. You get async/await syntax a la C#, much better than `.wait()` and `return future...()()}{{{}()()}` whatever nonsense, and no more weird fibers that may break (again) who knows when.

For type checking, instead of TS, how about [Flow](https://flowtype.org/)?

**Comment by rosen-vladimirov** [comment]
Hey @tailsu ,

Thanks for the suggestion and the valuable feedback.
AppBuilder CLI is a first-class citizen of the TypeScript world and we do not have plans to stop using TS at the moment. 
As per the fibers - yes, we have plans to remove them and use async/await instead. Stay tuned for more information in the near future.

I'll keep this issue open and update it once we have more information on the schedule of using async/await

**Comment by rosen-vladimirov** [comment]
@tailsu here's the PR that replaces fibers with async/await
https://github.com/Icenium/icenium-cli/pull/1623

**Comment by rosen-vladimirov** [comment]
Closing this - it's already implemented in master branch :)
