### ISSUE TITLE
Add a command to remove plugins 

### ISSUE THREAD

**Issue by paylocity-blackcobra** [Icenium/icenium-cli#178]
As part of the build process I want to be able to remove plugins. Example : jsHybugger is a plugin I use to add debugging ability for Android. I want to be able to remove that plugin for release builds.

**Comment by rosen-vladimirov** [comment]
Hi @paylocity-blackcobra ,

We've introduced .debug.abproject and .release.abproject.
When you add plugin, you can specify for which configuration you want to use it (by default it is used for both configs). For example
```
appbuilder plugin add leanplum --debug
```
Will add the plugin for debug configuration only and when you use 
```
appbuilder build android --release
```
the plugin will not be used for your package.

You can use the `--debug` and `--release` flags with `appbuilder plugin remove <plugin>` command as well.

Hope this helps. Feel free to contact us in case you have any problems or concerns.
