### ISSUE TITLE
Add the ability to set the AppManager Distribution Group 

### ISSUE THREAD

**Issue by paylocity-blackcobra** [Icenium/icenium-cli#387]
Add the ability to set the AppManager Distribution Group upon upload.

**Comment by rosen-vladimirov** [comment]
Hi @paylocity-blackcobra ,

We've already implemented this feature and you can use our latest official release in order to test in on your side.
The command that you have to execute is:
```
appbuilder appmanager upload <Platform> --group <Group ID> --group <Group ID> ...
```
Feel free to contact us in case you have any problems or concerns.
