### ISSUE TITLE
Add the ability to directly publish to AppManager

### ISSUE THREAD

**Issue by paylocity-blackcobra** [Icenium/icenium-cli#388]
Right now there is an upload command that pushes your app to AppManager. Then one has to manually publish it within AppManager. It will be nice if there is a publish command that directly does the publishing or maybe a parameter to the upload command

Example : appbuilder appmanager upload --publish

**Comment by rosen-vladimirov** [comment]
Hi @paylocity-blackcobra ,

We've already implemented this feature and you can use our latest official release in the following way:
```
appbuilder appmanager upload <platform> --publish
```
>NOTE: `--publish` -  If set, after the upload completes, automatically publishes the application package for the members of its distribution groups. You can set additional distribution groups with the --groups option.

Feel free to contact us in case you have any problems or concerns.
